# Generated by Django 3.2.3 on 2021-06-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20210607_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
